# Generated by Django 2.2 on 2020-03-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_tickets', '0002_auto_20200310_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsible',
            name='owner',
        ),
    ]
