# Generated by Django 2.2 on 2020-03-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_tickets', '0005_auto_20200314_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsible',
            name='owner',
        ),
    ]
