# Generated by Django 2.2 on 2020-03-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_tickets', '0006_remove_responsible_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='owner',
        ),
    ]
